---
- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - block:
        - name: determine hosts that are up
          wait_for_connection:
            timeout: 5
          vars:
            ansible_connection: ssh
        - name: add devices with connectivity to the "running_hosts" group
          group_by:
            key: "running_hosts"
      rescue:
        - debug: msg="cannot connect to {{inventory_hostname}}"

- hosts: running_hosts
  gather_facts: no
  ignore_errors: true
  ignore_unreachable: true
  no_log: true
  vars:
    # Use system python so apt package is available
    ansible_python_interpreter: "/usr/bin/env python3"
  tasks:

#    - debug: msg="{{ inventory_hostname }} is reachable"
    - name: update cache
      apt: update_cache=yes cache_valid_time=3600
    - name: Upgrade all apt packages
      apt: upgrade=dist
    - name: Check if a reboot is needed for Debian and Ubuntu boxes
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no
    - name: Reboot the Debian or Ubuntu server
      reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
